"""
Gemeinsame Konstanten
"""

# Deutsche Monatsnamen für Datumsformatierung

GERMAN_MONTH_NAMES = [
    "",  # Index 0 - nicht verwendet
    "Januar",
    "Februar",
    "März",
    "April",
    "Mai",
    "Juni",
    "Juli",
    "August",
    "September",
    "Oktober",
    "November",
    "Dezember",
]

# Hardware-Keywords für RSS-Feed Monitoring
HARDWARE_KEYWORDS = [
    "amd",
    "nvidia",
    "intel",
    "rtx",
    "ryzen",
    "arc",
    "gtx",
    "radeon",
    "rx",
    "grafikkarte",
    "cpu",
    "prozessor",
    "motherboard",
    "mainboard",
    "ram",
    "arbeitsspeicher",
    "ssd",
    "nvme",
    "festplatte",
    "speicher",
    "netzteil",
    "kühler",
    "lüfter",
    "gehäuse",
    "monitor",
    "display",
    "tastatur",
    "maus",
    "peripherie",
    "hardware",
    "msi",
    "asus",
    "gigabyte",
    "evga",
    "corsair",
    "cooler master",
    "be quiet",
    "fractal design",
    "nzxt",
    "thermaltake",
    "lenovo",
    "dell",
    "hp",
    "acer",
    "asrock",
    "phone",
    "tablet",
    "smartphone",
    "android",
    "ios",
    "apple",
    "samsung",
    "xiaomi",
    "oneplus",
    "huawei",
    "oppo",
    "realme",
    "google",
    "motorola",
    "sony",
    "lg",
    "nokia",
    "htc",
    "nothing phone",
    "smartwatch",
    "linux",
    "windows",
    "macos",
    "ubuntu",
    "fedora",
    "debian",
    "arch linux",
    "manjaro",
    "kde",
    "gnome",
    "nobara",
    "cachyos",
    "microsoft",
    "xbox",
    "nintendo",
    "playstation",
]

# Software-Keywords für RSS-Feed Monitoring
SOFTWARE_KEYWORDS = [
    "aida64",
    "hwinfo",
    "cpu-z",
    "gpu-z",
    "zentimings",
    "amd",
    "nvidia",
    "intel",
    "capframex",
    "afterburner",
    "rtss",
    "rivatuner",
]
